//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NezarkaTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NezarkaTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;Nezarka.net: Online Shopping for Books&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		table, th, td {
        ///			border: 1px solid black;
        ///			border-collapse: collapse;
        ///		}
        ///		table {
        ///			margin-bottom: 10px;
        ///		}
        ///		pre {
        ///			line-height: 70%;
        ///		}
        ///	&lt;/style&gt;
        ///	&lt;h1&gt;&lt;pre&gt;  v,&lt;br /&gt;Nezarka.NET: Online Shopping for Books&lt;/pre&gt;&lt;/h1&gt;
        ///	Jan, here is your menu:
        ///	&lt;table&gt;
        ///		&lt;tr&gt;
        ///			&lt;td&gt;&lt;a href=&quot;/Books&quot;&gt;Books&lt;/a&gt;&lt;/t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BookDetailsPageTemplate {
            get {
                return ResourceManager.GetString("BookDetailsPageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;Nezarka.net: Online Shopping for Books&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		table, th, td {
        ///			border: 1px solid black;
        ///			border-collapse: collapse;
        ///		}
        ///		table {
        ///			margin-bottom: 10px;
        ///		}
        ///		pre {
        ///			line-height: 70%;
        ///		}
        ///	&lt;/style&gt;
        ///	&lt;h1&gt;&lt;pre&gt;  v,&lt;br /&gt;Nezarka.NET: Online Shopping for Books&lt;/pre&gt;&lt;/h1&gt;
        ///	Jan, here is your menu:
        ///	&lt;table&gt;
        ///		&lt;tr&gt;
        ///			&lt;td&gt;&lt;a href=&quot;/Books&quot;&gt;Books&lt;/a&gt;&lt;/t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BooksMenuPageTemplate {
            get {
                return ResourceManager.GetString("BooksMenuPageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;Nezarka.net: Online Shopping for Books&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		table, th, td {
        ///			border: 1px solid black;
        ///			border-collapse: collapse;
        ///		}
        ///		table {
        ///			margin-bottom: 10px;
        ///		}
        ///		pre {
        ///			line-height: 70%;
        ///		}
        ///	&lt;/style&gt;
        ///	&lt;h1&gt;&lt;pre&gt;  v,&lt;br /&gt;Nezarka.NET: Online Shopping for Books&lt;/pre&gt;&lt;/h1&gt;
        ///	Pavel, here is your menu:
        ///	&lt;table&gt;
        ///		&lt;tr&gt;
        ///			&lt;td&gt;&lt;a href=&quot;/Books&quot;&gt;Books&lt;/a&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmptyShoppingCartPageTemplate {
            get {
                return ResourceManager.GetString("EmptyShoppingCartPageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Book details:
        ///	&lt;h2&gt;Going Postal&lt;/h2&gt;
        ///	&lt;p style=&quot;margin-left: 20px&quot;&gt;
        ///	Author: Terry Pratchett&lt;br /&gt;
        ///	Price: 28 EUR&lt;br /&gt;
        ///	&lt;/p&gt;
        ///	&lt;h3&gt;&amp;lt;&lt;a href=&quot;/ShoppingCart/Add/3&quot;&gt;Buy this book&lt;/a&gt;&amp;gt;&lt;/h3&gt;
        ///.
        /// </summary>
        internal static string ExpectedBookDetails {
            get {
                return ResourceManager.GetString("ExpectedBookDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	&lt;table&gt;
        ///		&lt;tr&gt;
        ///			&lt;td style=&quot;padding: 10px;&quot;&gt;
        ///				&lt;a href=&quot;/Books/Detail/1&quot;&gt;Lord of the Rings&lt;/a&gt;&lt;br /&gt;
        ///				Author: J. R. R. Tolkien&lt;br /&gt;
        ///				Price: 59 EUR &amp;lt;&lt;a href=&quot;/ShoppingCart/Add/1&quot;&gt;Buy&lt;/a&gt;&amp;gt;
        ///			&lt;/td&gt;
        ///			&lt;td style=&quot;padding: 10px;&quot;&gt;
        ///				&lt;a href=&quot;/Books/Detail/2&quot;&gt;Hobbit: There and Back Again&lt;/a&gt;&lt;br /&gt;
        ///				Author: J. R. R. Tolkien&lt;br /&gt;
        ///				Price: 49 EUR &amp;lt;&lt;a href=&quot;/ShoppingCart/Add/2&quot;&gt;Buy&lt;/a&gt;&amp;gt;
        ///			&lt;/td&gt;
        ///			&lt;td style=&quot;padding: 10px;&quot;&gt;
        ///				&lt;a href=&quot;/Books/Detail/3&quot;&gt;Going Postal&lt;/a&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedBookListView {
            get {
                return ResourceManager.GetString("ExpectedBookListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;tr&gt;
        ///			&lt;td&gt;&lt;a href=&quot;/Books/Detail/3&quot;&gt;TestBook&lt;/a&gt;&lt;/td&gt;
        ///			&lt;td&gt;3&lt;/td&gt;
        ///			&lt;td&gt;3 * 10 = 30 EUR&lt;/td&gt;
        ///			&lt;td&gt;&amp;lt;&lt;a href=&quot;/ShoppingCart/Remove/3&quot;&gt;Remove&lt;/a&gt;&amp;gt;&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///.
        /// </summary>
        internal static string ExpectedCartItemMultipleView {
            get {
                return ResourceManager.GetString("ExpectedCartItemMultipleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;tr&gt;
        ///			&lt;td&gt;&lt;a href=&quot;/Books/Detail/3&quot;&gt;TestBook&lt;/a&gt;&lt;/td&gt;
        ///			&lt;td&gt;1&lt;/td&gt;
        ///			&lt;td&gt;10 EUR&lt;/td&gt;
        ///			&lt;td&gt;&amp;lt;&lt;a href=&quot;/ShoppingCart/Remove/3&quot;&gt;Remove&lt;/a&gt;&amp;gt;&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///.
        /// </summary>
        internal static string ExpectedCartItemSingleView {
            get {
                return ResourceManager.GetString("ExpectedCartItemSingleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	&lt;table&gt;
        ///		&lt;tr&gt;
        ///			&lt;th&gt;Title&lt;/th&gt;
        ///			&lt;th&gt;Count&lt;/th&gt;
        ///			&lt;th&gt;Price&lt;/th&gt;
        ///			&lt;th&gt;Actions&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///		&lt;tr&gt;
        ///			&lt;td&gt;&lt;a href=&quot;/Books/Detail/2&quot;&gt;TestBook2&lt;/a&gt;&lt;/td&gt;
        ///			&lt;td&gt;3&lt;/td&gt;
        ///			&lt;td&gt;3 * 10 = 30 EUR&lt;/td&gt;
        ///			&lt;td&gt;&amp;lt;&lt;a href=&quot;/ShoppingCart/Remove/2&quot;&gt;Remove&lt;/a&gt;&amp;gt;&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///		&lt;tr&gt;
        ///			&lt;td&gt;&lt;a href=&quot;/Books/Detail/1&quot;&gt;TestBook&lt;/a&gt;&lt;/td&gt;
        ///			&lt;td&gt;1&lt;/td&gt;
        ///			&lt;td&gt;10 EUR&lt;/td&gt;
        ///			&lt;td&gt;&amp;lt;&lt;a href=&quot;/ShoppingCart/Remove/1&quot;&gt;Remove&lt;/a&gt;&amp;gt;&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///	&lt;/table&gt;
        ///	Total price of all items: 40 EUR
        ///.
        /// </summary>
        internal static string ExpectedCartTableView {
            get {
                return ResourceManager.GetString("ExpectedCartTableView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	&lt;h1&gt;&lt;pre&gt;  v,&lt;br /&gt;Nezarka.NET: Online Shopping for Books&lt;/pre&gt;&lt;/h1&gt;
        ///	Jan, here is your menu:
        ///	&lt;table&gt;
        ///		&lt;tr&gt;
        ///			&lt;td&gt;&lt;a href=&quot;/Books&quot;&gt;Books&lt;/a&gt;&lt;/td&gt;
        ///			&lt;td&gt;&lt;a href=&quot;/ShoppingCart&quot;&gt;Cart (0)&lt;/a&gt;&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///	&lt;/table&gt;
        ///.
        /// </summary>
        internal static string ExpectedCustomerHeader {
            get {
                return ResourceManager.GetString("ExpectedCustomerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 			&lt;td style=&quot;padding: 10px;&quot;&gt;
        ///				&lt;a href=&quot;/Books/Detail/1&quot;&gt;Lord of the Rings&lt;/a&gt;&lt;br /&gt;
        ///				Author: J. R. R. Tolkien&lt;br /&gt;
        ///				Price: 59 EUR &amp;lt;&lt;a href=&quot;/ShoppingCart/Add/1&quot;&gt;Buy&lt;/a&gt;&amp;gt;
        ///			&lt;/td&gt;
        ///.
        /// </summary>
        internal static string ExpectedListItemView {
            get {
                return ResourceManager.GetString("ExpectedListItemView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	&lt;style type=&quot;text/css&quot;&gt;
        ///		table, th, td {
        ///			border: 1px solid black;
        ///			border-collapse: collapse;
        ///		}
        ///		table {
        ///			margin-bottom: 10px;
        ///		}
        ///		pre {
        ///			line-height: 70%;
        ///		}
        ///	&lt;/style&gt;
        ///.
        /// </summary>
        internal static string ExpectedStyleSetup {
            get {
                return ResourceManager.GetString("ExpectedStyleSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;Nezarka.net: Online Shopping for Books&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;p&gt;Invalid request.&lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;        ///.
        /// </summary>
        internal static string InvalidRequestPageTemplate {
            get {
                return ResourceManager.GetString("InvalidRequestPageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;title&gt;Nezarka.net: Online Shopping for Books&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		table, th, td {
        ///			border: 1px solid black;
        ///			border-collapse: collapse;
        ///		}
        ///		table {
        ///			margin-bottom: 10px;
        ///		}
        ///		pre {
        ///			line-height: 70%;
        ///		}
        ///	&lt;/style&gt;
        ///	&lt;h1&gt;&lt;pre&gt;  v,&lt;br /&gt;Nezarka.NET: Online Shopping for Books&lt;/pre&gt;&lt;/h1&gt;
        ///	Jan, here is your menu:
        ///	&lt;table&gt;
        ///		&lt;tr&gt;
        ///			&lt;td&gt;&lt;a href=&quot;/Books&quot;&gt;Books&lt;/a&gt;&lt;/t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShoppingCartPageTemplate {
            get {
                return ResourceManager.GetString("ShoppingCartPageTemplate", resourceCulture);
            }
        }
    }
}
