//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReflectorSerializerTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReflectorSerializerTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Person&gt;
        ///  &lt;FirstName&gt;Pavel&lt;/FirstName&gt;
        ///  &lt;LastName&gt;Jezek&lt;/LastName&gt;
        ///  &lt;HomeAddress&gt;
        ///    &lt;Address&gt;
        ///      &lt;Street&gt;Patkova&lt;/Street&gt;
        ///      &lt;City&gt;Prague&lt;/City&gt;
        ///    &lt;/Address&gt;
        ///  &lt;/HomeAddress&gt;
        ///  &lt;WorkAddress&gt;
        ///    &lt;Address&gt;
        ///      &lt;Street&gt;Malostranske namesti&lt;/Street&gt;
        ///      &lt;City&gt;Prague&lt;/City&gt;
        ///    &lt;/Address&gt;
        ///  &lt;/WorkAddress&gt;
        ///  &lt;Employees&gt;
        ///    &lt;Person&gt;
        ///      &lt;FirstName&gt;Jiri&lt;/FirstName&gt;
        ///      &lt;LastName&gt;Vesely&lt;/LastName&gt;
        ///      &lt;HomeAddress&gt;
        ///        &lt;Address&gt;
        ///          &lt;Street&gt;Ctvrtkova&lt;/Street&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultIndent {
            get {
                return ResourceManager.GetString("DefaultIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Person&gt;
        ///  &lt;FirstName&gt;
        ///    &lt;Char&gt;P&lt;/Char&gt;
        ///    &lt;Char&gt;a&lt;/Char&gt;
        ///    &lt;Char&gt;v&lt;/Char&gt;
        ///    &lt;Char&gt;e&lt;/Char&gt;
        ///    &lt;Char&gt;l&lt;/Char&gt;
        ///  &lt;/FirstName&gt;
        ///  &lt;LastName&gt;
        ///    &lt;Char&gt;J&lt;/Char&gt;
        ///    &lt;Char&gt;e&lt;/Char&gt;
        ///    &lt;Char&gt;z&lt;/Char&gt;
        ///    &lt;Char&gt;e&lt;/Char&gt;
        ///    &lt;Char&gt;k&lt;/Char&gt;
        ///  &lt;/LastName&gt;
        ///  &lt;HomeAddress&gt;
        ///    &lt;Address&gt;
        ///      &lt;Street&gt;
        ///        &lt;Char&gt;P&lt;/Char&gt;
        ///        &lt;Char&gt;a&lt;/Char&gt;
        ///        &lt;Char&gt;t&lt;/Char&gt;
        ///        &lt;Char&gt;k&lt;/Char&gt;
        ///        &lt;Char&gt;o&lt;/Char&gt;
        ///        &lt;Char&gt;v&lt;/Char&gt;
        ///        &lt;Char&gt;a&lt;/Char&gt;
        ///      &lt;/Street&gt;
        ///      &lt;Ci [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Indent2EnumerableString {
            get {
                return ResourceManager.GetString("Indent2EnumerableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Person&gt;
        ///    &lt;FirstName&gt;Pavel&lt;/FirstName&gt;
        ///    &lt;LastName&gt;Jezek&lt;/LastName&gt;
        ///    &lt;HomeAddress&gt;
        ///        &lt;Address&gt;
        ///            &lt;Street&gt;Patkova&lt;/Street&gt;
        ///            &lt;City&gt;Prague&lt;/City&gt;
        ///        &lt;/Address&gt;
        ///    &lt;/HomeAddress&gt;
        ///    &lt;WorkAddress&gt;
        ///        &lt;Address&gt;
        ///            &lt;Street&gt;Malostranske namesti&lt;/Street&gt;
        ///            &lt;City&gt;Prague&lt;/City&gt;
        ///        &lt;/Address&gt;
        ///    &lt;/WorkAddress&gt;
        ///    &lt;Employees&gt;
        ///        &lt;Person&gt;
        ///            &lt;FirstName&gt;Jiri&lt;/FirstName&gt;
        ///            &lt;LastName&gt;Vesely&lt;/LastName&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IndentBy4 {
            get {
                return ResourceManager.GetString("IndentBy4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Int32&gt;42&lt;/Int32&gt;.
        /// </summary>
        internal static string SingleInt {
            get {
                return ResourceManager.GetString("SingleInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;String&gt;Hello&lt;/String&gt;.
        /// </summary>
        internal static string SingleString {
            get {
                return ResourceManager.GetString("SingleString", resourceCulture);
            }
        }
    }
}
